<a href="https://colab.research.google.com/github/douglasvervalen/IC/blob/main/Gerador.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import random
from sympy import isprime

# Função para verificar se um número é de Fibonacci
def is_fibonacci(n):
    x, y = 0, 1
    while y < n:
        x, y = y, x + y
    return y == n

# Função principal para gerar os números
def gerar_numeros():
    while True:
        numeros = random.sample(range(1, 61), 6)

        impares = [num for num in numeros if num % 2 != 0]
        pares = [num for num in numeros if num % 2 == 0]
        primos = [num for num in numeros if isprime(num)]
        multiplos_de_3 = [num for num in numeros if num % 3 == 0]
        fibonacci = [num for num in numeros if is_fibonacci(num)]

        soma = sum(numeros)

        if (len(impares) == 3 and
            len(pares) == 3 and
            len(primos) == 1 and
            len(multiplos_de_3) == 3 and
            len(fibonacci) == 0 and
            228 <= soma <= 229):
            return numeros, impares, pares, primos, multiplos_de_3, fibonacci, soma

numeros, impares, pares, primos, multiplos_de_3, fibonacci, soma = gerar_numeros()

print(f"Números gerados: {numeros} ({len(numeros)})")
print(f"Números ímpares: {impares} ({len(impares)})")
print(f"Números pares: {pares} ({len(pares)})")
print(f"Números primos: {primos} ({len(primos)})")
print(f"Números múltiplos de 3: {multiplos_de_3} ({len(multiplos_de_3)})")
print(f"Números de Fibonacci: {fibonacci} ({len(fibonacci)})")
print(f"Soma total: {soma}")

Números gerados: [36, 45, 17, 58, 46, 27] (6)
Números ímpares: [45, 17, 27] (3)
Números pares: [36, 58, 46] (3)
Números primos: [17] (1)
Números múltiplos de 3: [36, 45, 27] (3)
Números de Fibonacci: [] (0)
Soma total: 229

In [3]:

import pandas as pd

# Define the extracted numbers
concursos = {
    "2747": [46, 28, 51, 27, 53, 24],
    "2746": [22, 27, 30, 43, 51, 56],
    "2745": [2, 5, 7, 11, 52, 57],
    "2744": [10, 25, 26, 33, 34, 38],
    "2743": [13, 25, 27, 30, 37, 53],
    "2742": [2, 11, 25, 32, 37, 57],
    "2741": [1, 33, 35, 39, 42, 56],
    "2740": [13, 16, 17, 34, 41, 47],
    "2739": [19, 25, 37, 45, 47, 53],
    "2738": [2, 19, 25, 44, 46, 60],
    "2737": [16, 20, 30, 34, 37, 45],
    "2736": [11, 17, 24, 26, 35, 43],
    "2735": [5, 33, 46, 47, 53, 59],
    "2734": [21, 27, 35, 48, 59, 60],
}

# Define the Fibonacci sequence up to 60
fibonacci_set = {0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55}

# Function to classify numbers
def classify_numbers(numbers):
    primes = []
    multiples_of_3 = []
    fibonacci = []
    odd = []
    even = []

    for number in numbers:
        # Check if prime
        if number > 1 and all(number % i != 0 for i in range(2, int(number ** 0.5) + 1)):
            primes.append(number)

        # Check if multiple of 3
        if number % 3 == 0:
            multiples_of_3.append(number)

        # Check if in Fibonacci sequence
        if number in fibonacci_set:
            fibonacci.append(number)

        # Check if odd or even
        if number % 2 == 0:
            even.append(number)
        else:
            odd.append(number)

    return {
        "primes": primes,
        "multiples_of_3": multiples_of_3,
        "fibonacci": fibonacci,
        "odd": odd,
        "even": even,
        "sum": sum(numbers)
    }

# Create a dataframe to store the results
df_results = pd.DataFrame(columns=["Concurso", "Primes", "Multiples of 3", "Fibonacci", "Odd", "Even", "Sum"])

# Populate the dataframe with the classified results
for concurso, numbers in concursos.items():
    classified = classify_numbers(numbers)
    df_results = df_results._append({
        "Concurso": concurso,
        "Primes": len(classified["primes"]),
        "Multiples of 3": len(classified["multiples_of_3"]),
        "Fibonacci": len(classified["fibonacci"]),
        "Odd": len(classified["odd"]),
        "Even": len(classified["even"]),
        "Sum": classified["sum"]
    }, ignore_index=True)

df_results

   Concurso Primes Multiples of 3 Fibonacci Odd Even  Sum
0      2747      1              3         0   3    3  229
1      2746      1              3         0   3    3  229
2      2745      4              1         2   4    2  134
3      2744      0              1         1   2    4  166
4      2743      3              2         1   5    1  185
5      2742      3              1         1   4    2  164
6      2741      0              3         1   4    2  206
7      2740      4              0         2   4    2  168
8      2739      4              1         0   6    0  226
9      2738      2              1         1   2    4  196
10     2737      1              2         1   2    4  182
11     2736      3              1         0   4    2  156
12     2735      4              1         1   5    1  243
13     2734      1              4         1   4    2  250